services:
  # A Docker web service
  - type: web
    name: compendia-API
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('stopwords')"
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
